<Project>
  <PropertyGroup>
    <Version>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</Version>
    <Authors>FUYUKI YONEYAMA</Authors>
    <Copyright>Copyright (c) 2026 FUYUKI YONEYAMA</Copyright>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>
</Project>
