<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>XInputReader</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../InputTools.Common/InputTools.Common.csproj" /></ItemGroup>
</Project>
